spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?ApplicationName=spring_app
    username: postgres
    password: pass
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false